### ISSUE TITLE
Crashlytics integration

### ISSUE THREAD

**Issue by emartynov** [emartynov/UrlSetter#4]

**Comment by ghost** [comment]
Since crashlytics is non-free software, is there an easy way to strip it? E.g. could you provide a pure-floss build flavour?

**Comment by emartynov** [comment]
@krt16s can you explain why it is not free for you?

**Comment by ghost** [comment]
I was talking about freedom, not about the price tag. With crashlytics, you just download or include a closed-source, binary library, which is something we at f-droid.org (a free/libre/open-source app repository) simply cannot do. So maybe a free flavour is possible or (depending if it suits your usecase) the opensource http://www.acra.ch/ can be used to  replace crashlytics.
